#!/usr/bin/env bash
# Bash (init) script that manages the file "manage_my_process"

case "$1" in
	start)
	./manage_my_process &
	echo "$$" > /var/run/my_process.pid
	echo "manage_my_process started"
	;;
	stop)
	pkill -f -KILL manage_my_process
	rm /var/run/my_process.pid
	echo "manage_my_process stopped"
	;;
	restart)
	pkill -f -KILL manage_my_process
	rm /var/run/my_process.pid
	./manage_my_process &
	echo $$ > /var/run/my_process.pid
	echo "manage_my_process restarted"
	;;
	*)
	echo "usage: $0 <start|stop|restart>"
	exit 1
esac
