#!/usr/bin/env bash
#displays numbers from 1 to 100
#Displays FizzBuzz when number is a mutiple of 3 and 5
#Displays Fizz when number is a multiple of 3
#Displays Buzz when number is a multiple of 5
#otherwise it displays the number in a lit format
for i in {1..100}
do
	if (( i % 15 == 0 ))
	then
		echo "FizzBuzz"
	elif (( i % 5 == 0 ))
	then
		echo "Buzz"
	elif (( i % 3 == 0 ))
	then
		echo "Fizz"
	else
		echo "$i"
	fi
done
