#!/usr/bin/env bash
#Displays the numbers 1 to 20 and:
#displays 4 and then bad luck from China
#displays 9 and then bad luck from Japan
#displays 17 and then bad luck from Italy

x=1
while [ $x -le 20 ]
do
	echo "$x"
	case "$x" in
		"4") echo "bad luck from China"
		;;
		"9") echo "bad luck from Japan"
		;;
		"17") echo "bad luck from Italy"
		;;
	esac
	x=$(( x + 1 ))
done
