#!/usr/bin/env bash
#Displays the time fo r12 hours and 59 minutes:
#display hours from 0 to 10
#display minutes from 1 to 59
h=0
while [ $h -le 12 ]
do
	echo "Hour: $h"
	m=1
	while [ $m -le 59 ]
	do
		echo "$m"
		m=$(( m + 1 ))		
	done
	h=$(( h + 1 ))
done
