#!/usr/bin/env bash
#Bash script that displays the content of the current directory
#in a list format
#only name is displayed
#Use only for loop
#Do not display hidden files.
for i in *
do
	echo "${i#*-}" #prints i without the characters preceeding "-"; i%-* will print i without the characters after "-"
done

